version: '3.8'

services:
  # Flask App service
  app:
    build: .
    container_name: webshop_app
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development
    ports:
      - "5000:5000"
    depends_on:
      - db  # Ensure the database service starts first
    volumes:
      - .:/app  # Mount the current directory to /app in the container
    restart: always

  # MySQL Database service
  db:
    image: mysql:5.7  # Use MySQL 5.7 image
    container_name: webshop_db
    environment:
      MYSQL_ROOT_PASSWORD: root  # Set root password for MySQL
      MYSQL_DATABASE: webshop    # Create 'webshop' database
    ports:
      - "3308:3308"  # Expose MySQL port
    volumes:
      - db_data:/var/lib/mysql
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
    restart: always

volumes:
  db_data:
