CREATE DATABASE webshop;

USE webshop;

CREATE TABLE product ( id INT AUTO_INCREMENT PRIMARY KEY,
category VARCHAR(100) NOT NULL,
 image VARCHAR(255) NOT NULL,
name VARCHAR(100) NOT NULL,
description TEXT NOT NULL,
price FLOAT NOT NULL );


CREATE TABLE Inventory (
 id INT AUTO_INCREMENT PRIMARY KEY,
 product_id INT NOT NULL UNIQUE,
 quantity INT NOT NULL DEFAULT 0,
 FOREIGN KEY (product_id) REFERENCES product(id) ON DELETE CASCADE ON UPDATE CASCADE);
